import fs from "node:fs";
import path from "node:path";
import { config, projectDir } from "../config.js";
import type { AgentInfo } from "../docker.js";
import type { AllModel } from "../piModels.js";
import type { AttachedAgent, ContainerRuntime, LifecycleEvent, SpawnOptions } from "../runtime.js";
import { FakePi, type FakePiHistoryEntry, type MockModel, type StreamGranularity } from "./fake-pi.js";

/**
 * MockRuntime — in-memory `ContainerRuntime` for `MOCK_VPS=1` dev mode
 * (mock-VPS plan, Phase 1). No Docker, no jarvis, no host mounts: agents live
 * in a `Map<string, MockAgent>`, each owning a FakePi session.
 *
 * Seeding: loads `testdata/mock/scenarios.json` when present (generated by
 * `scripts/mock-seed.mjs`; `MOCK_SCENARIO=name` selects, unknown name fails
 * fast with the valid list). Without the file — e.g. Phase-1 acceptance —
 * seeds one hardcoded demo agent as fallback.
 */

interface MockAgent {
  id: string;
  project: string;
  dir: string;
  name: string;
  origin: string | null;
  generalChat: boolean;
  state: string;
  startedAt: string;
  fakePi: FakePi;
}

interface ScenarioAgentConfig {
  project: string;
  name?: string;
  origin?: string | null;
  readOnly?: boolean;
  generalChat?: boolean;
  granularity?: StreamGranularity;
  history?: FakePiHistoryEntry[];
}

interface ScenarioConfig {
  defaultGranularity?: StreamGranularity;
  agents: ScenarioAgentConfig[];
}

export function scenariosFile(): string {
  return process.env.MOCK_SCENARIOS_FILE ?? path.join(process.cwd(), "testdata/mock/scenarios.json");
}

export function mockModelsPath(): string {
  return process.env.MOCK_MODELS_FILE ?? path.join(process.cwd(), "testdata/mock/models.json");
}

function loadModels(): MockModel[] | undefined {
  try {
    const raw = fs.readFileSync(mockModelsPath(), "utf8");
    const parsed = JSON.parse(raw) as Array<{
      provider: string;
      id: string;
      name?: string;
      contextWindow?: number;
    }>;
    if (Array.isArray(parsed) && parsed.length > 0) return parsed;
  } catch {
    /* no fixture yet — FakePi falls back to its built-in default */
  }
  return undefined;
}

export class MockRuntime implements ContainerRuntime {
  private agents = new Map<string, MockAgent>();
  private listeners = new Set<(e: LifecycleEvent) => void>();
  private seq = 0;
  private models: MockModel[] | undefined;

  constructor() {
    this.models = loadModels();
    this.seed();
  }

  list(): Promise<AgentInfo[]> {
    const out: AgentInfo[] = [...this.agents.values()].map((a) => ({
      id: a.id,
      name: a.name,
      project: a.project,
      origin: a.origin,
      state: a.state,
      startedAt: a.startedAt,
      live: null,
      sessionName: null,
      generalChat: a.generalChat,
      model: null,
      thinkingLevel: null,
    }));
    out.sort((x, y) => x.project.localeCompare(y.project) || x.name.localeCompare(y.name));
    return Promise.resolve(out);
  }

  labels(id: string): Promise<Record<string, string> | null> {
    const a = this.agents.get(id);
    if (!a) return Promise.resolve(null);
    const labels: Record<string, string> = {
      "agent.kind": "pi",
      "agent.project": a.project,
    };
    if (a.origin) labels["agent.origin"] = a.origin;
    if (a.generalChat) labels["agent.generalchat"] = "true";
    return Promise.resolve(labels);
  }

  attach(id: string): Promise<AttachedAgent> {
    const a = this.agents.get(id);
    if (!a) return Promise.reject(new Error(`unknown mock agent: ${id}`));
    return Promise.resolve(a.fakePi.createAttach());
  }

  stopAndRemove(id: string): Promise<void> {
    const a = this.agents.get(id);
    if (!a) return Promise.resolve();
    // Close pipes first: drives the bridge's markExited path exactly like a
    // real stop. The terminate route's bridges.get(id)?.destroy() call is
    // unchanged and still produces the multi-tab exited broadcast.
    // Delete before emitting so a client refetching on agents_changed never
    // sees the ghost: prod removes the container, so the list drops it too.
    a.fakePi.close();
    this.agents.delete(id);
    this.emit({ action: "die", id });
    this.emit({ action: "destroy", id });
    return Promise.resolve();
  }

  listModels(): Promise<AllModel[]> {
    // Mock mode serves the deterministic fixture; prod lists via jarvis models.
    try {
      const raw = fs.readFileSync(mockModelsPath(), "utf8");
      const parsed = JSON.parse(raw) as AllModel[];
      if (Array.isArray(parsed)) return Promise.resolve(parsed);
    } catch {
      /* fall through to the helpful error below */
    }
    return Promise.reject(
      new Error("mock models fixture missing (run npm run mock-seed)"),
    );
  }

  spawn(opts: SpawnOptions): Promise<string> {
    const id = `mock-${++this.seq}`;
    const project = path.basename(opts.project);
    const dir = opts.project;
    let history: FakePiHistoryEntry[] | undefined;
    let resumeName: string | null = null;
    if (opts.sessionPath) {
      const loaded = FakePi.loadResume(opts.sessionPath);
      if (loaded) {
        history = loaded.entries;
        resumeName = loaded.name;
      }
    }
    const fakePi = new FakePi({
      id,
      project,
      // No placeholder name: fresh spawns stay untitled until the first
      // message titles them (Group F). Resumes keep their session name.
      ...(opts.name !== undefined
        ? { name: opts.name }
        : resumeName !== null
          ? { name: resumeName }
          : {}),
      readOnly: opts.readOnly,
      generalChat: opts.generalChat,
      granularity: (process.env.MOCK_GRANULARITY as StreamGranularity | undefined) ?? "word",
      models: this.models,
      history,
    });
    this.agents.set(id, {
      id,
      project,
      dir,
      name: id,
      origin: "dashboard",
      generalChat: !!opts.generalChat,
      state: "running",
      startedAt: new Date().toISOString(),
      fakePi,
    });
    this.emit({ action: "start", id });
    return Promise.resolve(id);
  }

  onLifecycle(cb: (e: LifecycleEvent) => void): () => void {
    this.listeners.add(cb);
    return () => {
      this.listeners.delete(cb);
    };
  }

  // ---- seeding ------------------------------------------------------------

  private emit(e: LifecycleEvent): void {
    for (const cb of this.listeners) {
      try {
        cb(e);
      } catch {
        /* listener failure must not break the emitter */
      }
    }
  }

  private addSeeded(cfg: ScenarioAgentConfig, defaultGranularity?: StreamGranularity): void {
    const id = `mock-${++this.seq}`;
    const dir = projectDir(cfg.project) ?? path.join(config.projectsDir, cfg.project);
    const fakePi = new FakePi({
      id,
      project: cfg.project,
      name: cfg.name ?? "mock chat",
      readOnly: cfg.readOnly,
      generalChat: cfg.generalChat,
      granularity: cfg.granularity ?? defaultGranularity ?? "word",
      models: this.models,
      history: cfg.history,
    });
    this.agents.set(id, {
      id,
      project: cfg.project,
      dir,
      name: id,
      origin: cfg.origin ?? null,
      generalChat: !!cfg.generalChat,
      state: "running",
      startedAt: new Date().toISOString(),
      fakePi,
    });
  }

  private seed(): void {
    let raw: string;
    try {
      raw = fs.readFileSync(scenariosFile(), "utf8");
    } catch {
      throw new Error(
        `mock scenarios file not found: ${scenariosFile()} (run "npm run mock-seed" from dashboard/ first)`,
      );
    }
    let scenarios: Record<string, ScenarioConfig>;
    try {
      scenarios = JSON.parse(raw) as Record<string, ScenarioConfig>;
    } catch (err) {
      throw new Error(
        `mock scenarios file is not valid JSON: ${scenariosFile()}: ${err instanceof Error ? err.message : err}`,
      );
    }
    const want = process.env.MOCK_SCENARIO ?? "sidebar-full";
    const scenario = scenarios[want];
    if (!scenario) {
      const valid = Object.keys(scenarios).sort().join(", ") || "(none)";
      throw new Error(`unknown MOCK_SCENARIO=${JSON.stringify(want)} (valid: ${valid})`);
    }
    for (const cfg of scenario.agents ?? []) {
      this.addSeeded(cfg, scenario.defaultGranularity);
    }
  }
}
